function [sub_sample] = sub_sample_points(I_blur, chosen_points, i)
sub_sample(1) = I_blur(chosen_points(i,1), chosen_points(i,2) - 4);
sub_sample(2) = I_blur(chosen_points(i,1), chosen_points(i,2) + 4);
sub_sample(3) = I_blur(chosen_points(i,1) - 4, chosen_points(i,2));
sub_sample(4) = I_blur(chosen_points(i,1) + 4, chosen_points(i,2));
sub_sample(5) = I_blur(chosen_points(i,1) + 3, chosen_points(i,2) - 3);
sub_sample(6) = I_blur(chosen_points(i,1) - 3, chosen_points(i,2) + 3);
sub_sample(7) = I_blur(chosen_points(i,1) + 3, chosen_points(i,2) + 3);
sub_sample(8) = I_blur(chosen_points(i,1) - 3, chosen_points(i,2) - 3);
sub_sample(9) = I_blur(chosen_points(i,1), chosen_points(i,2) - 2);
sub_sample(10) = I_blur(chosen_points(i,1), chosen_points(i,2) + 2);
sub_sample(11) = I_blur(chosen_points(i,1) - 2, chosen_points(i,2));
sub_sample(12) = I_blur(chosen_points(i,1) + 2, chosen_points(i,2));
sub_sample(13) = I_blur(chosen_points(i,1) - 1, chosen_points(i,2) - 1);
sub_sample(14) = I_blur(chosen_points(i,1) + 1, chosen_points(i,2) + 1);
sub_sample(15) = I_blur(chosen_points(i,1) - 1, chosen_points(i,2) + 1);
sub_sample(16) = I_blur(chosen_points(i,1) + 1, chosen_points(i,2) - 1);
sub_sample(17) = I_blur(chosen_points(i,1), chosen_points(i,2));